#!/usr/bin/env bash
#
# lib/config_templates.sh - Config template generation for nunchux
#

# Guard against double-sourcing
[[ -n "${NUNCHUX_LIB_CONFIG_TEMPLATES_LOADED:-}" ]] && return
NUNCHUX_LIB_CONFIG_TEMPLATES_LOADED=1

# Known TUI tools with their descriptions
# Format: "command:name:description:category"
KNOWN_TOOLS=(
  "lazygit:lazygit:Git TUI:git"
  "lazydocker:lazydocker:Docker TUI:docker"
  "btop:btop:System monitor:system"
  "htop:htop:Process viewer:system"
  "ncdu:ncdu:Disk usage analyzer:system"
  "nvim:neovim:Neovim editor:editor"
  "k9s:k9s:Kubernetes TUI:k8s"
  "tig:tig:Git history browser:git"
  "ranger:ranger:File manager:files"
  "lf:lf:File manager:files"
  "yazi:yazi:File manager:files"
  "nnn:nnn:File manager:files"
  "broot:broot:File tree navigator:files"
)

# Detect which tools are installed
# Outputs: lines of "command:name:description:category" for installed tools
detect_installed_tools() {
  for tool_spec in "${KNOWN_TOOLS[@]}"; do
    local cmd="${tool_spec%%:*}"
    if command -v "$cmd" &>/dev/null; then
      echo "$tool_spec"
    fi
  done
}

# Generate minimal safe config (works everywhere)
# Usage: generate_minimal_config CONFIG_FILE
generate_minimal_config() {
  local config_file="$1"
  local config_dir="${config_file%/*}"

  mkdir -p "$config_dir"

  cat > "$config_file" << 'EOF'
# Nunchux Configuration
# This is a minimal config - add more apps as needed.
# See docs/configuration.md for all options.

[settings]
popup_width = 90%
popup_height = 90%

# Order section - controls menu item order
# Items listed here appear first, in this order
# Unlisted items are appended alphabetically
# [order]
# htop
# system
# configs
# taskrunner:just

# Example app (uncomment and modify):
# [app:htop]
# cmd = htop
# desc = Process viewer

# Example submenu:
# [menu:system]
# status = echo "load: $(cut -d' ' -f1 /proc/loadavg)"

# Example directory browser:
# [dirbrowser:configs]
# directory = ~/.config
# depth = 2
EOF
}

# Generate config from selected tools
# Usage: generate_detected_config CONFIG_FILE SELECTED_TOOLS_ARRAY
# SELECTED_TOOLS_ARRAY contains lines in format "command:name:description:category"
generate_detected_config() {
  local config_file="$1"
  local -n _selected_tools=$2
  local config_dir="${config_file%/*}"

  mkdir -p "$config_dir"

  {
    echo "# Nunchux Configuration"
    echo "# Generated by setup wizard"
    echo "# See docs/configuration.md for all options."
    echo ""
    echo "[settings]"
    echo "popup_width = 90%"
    echo "popup_height = 90%"
    echo ""
    echo "# Order section - controls menu item order"
    echo "# Items listed here appear first, in this order"
    echo "# Unlisted items are appended alphabetically"
    echo "# [order]"
    echo "# app_name"
    echo "# submenu_name"
    echo "# taskrunner:just"
    echo ""

    # Group tools by category
    local -A by_category
    for tool_spec in "${_selected_tools[@]}"; do
      local cmd="${tool_spec%%:*}"
      local rest="${tool_spec#*:}"
      local name="${rest%%:*}"
      rest="${rest#*:}"
      local desc="${rest%%:*}"
      local category="${rest#*:}"

      by_category["$category"]+="$tool_spec"$'\n'
    done

    # Output apps
    local has_system=false
    for tool_spec in "${_selected_tools[@]}"; do
      local cmd="${tool_spec%%:*}"
      local rest="${tool_spec#*:}"
      local name="${rest%%:*}"
      rest="${rest#*:}"
      local desc="${rest%%:*}"
      local category="${rest#*:}"

      # Put system tools in a submenu
      if [[ "$category" == "system" ]]; then
        has_system=true
        continue
      fi

      echo "[app:$name]"
      # yazi needs special handling to avoid breaking tmux
      if [[ "$cmd" == "yazi" ]]; then
        echo "cmd = tmux new-session yazi --cwd-file={tmp} \\; set status off"
      else
        echo "cmd = $cmd"
      fi
      [[ -n "$desc" ]] && echo "desc = $desc"
      echo ""
    done

    # Create system submenu if needed
    if [[ "$has_system" == "true" ]]; then
      echo "[menu:system]"
      echo "status = echo \"load: \$(cut -d' ' -f1 /proc/loadavg)\""
      echo ""

      for tool_spec in "${_selected_tools[@]}"; do
        local cmd="${tool_spec%%:*}"
        local rest="${tool_spec#*:}"
        local name="${rest%%:*}"
        rest="${rest#*:}"
        local desc="${rest%%:*}"
        local category="${rest#*:}"

        if [[ "$category" == "system" ]]; then
          echo "[app:system/$name]"
          echo "cmd = $cmd"
          [[ -n "$desc" ]] && echo "desc = $desc"
          echo ""
        fi
      done
    fi

    # Add helpful comments
    echo "# Directory browsers - browse files in a directory"
    echo "# [dirbrowser:configs]"
    echo "# directory = ~/.config"
    echo "# depth = 2"
    echo "# sort = modified-folder"
    echo ""
    echo "# Task runners - run project tasks"
    echo "# [taskrunner:just]"
    echo "# enabled = true"
  } > "$config_file"
}

# vim: ft=bash ts=2 sw=2 et
